# Generated by Django 4.2.19 on 2025-03-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_alter_blooddonate_id_alter_donor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/Donor/image.png', upload_to='profile_pic/Donor/'),
        ),
    ]
