# Generated by Django 4.2.19 on 2025-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_remove_donor_last_donation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='health_check_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
