# Generated by Django 4.2.19 on 2025-03-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_bloodrequest'),
        ('blood', '0005_alter_bloodrequest_id_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_by_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='patient.patient'),
        ),
    ]
