# Generated by Django 4.2.19 on 2025-03-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_delete_bloodrequest'),
        ('blood', '0006_alter_bloodrequest_request_by_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_by_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
