# Generated by Django 4.2.19 on 2025-04-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_emailcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='success_count',
            field=models.IntegerField(default=0),
        ),
    ]
